name: RudraCheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    steps:
      - name: Rudra 
        uses: sslab-gatech/Rudra@master
